version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name kadai4 --s3-location s3://s3-cicd-kadai/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src